
import j_6 from '../../../images/j_6.png';
export const ProjectData = [
    {
        key : "1",
        src:j_6,
        width:1,
        height:1,
        alternate:"jm_5",
        display: `Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        key : "2",
        src:j_6,
        width:1,
        height:1,
        alternate:"jm_5",
        display: `Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        key : "3",
        src:j_6,
        width:1,
        height:1,
        alternate:"j_5",
        display: `Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        key : "4",
        src:j_6,
        width:1,
        height:1,
        alternate:"j_5",
        display: `Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        key : "5",
        src:j_6,
        width:1,
        height:1,
        alternate:"j_5",
        display: `Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        key : "6",
        src:j_6,
        width:1,
        height:1,
        alternate:"j_8",
        display: `Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        key : "7",
        src:j_6,
        width:1,
        height:1,
        alternate:"jm_1",
        display: `Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        key : "8",
        src:j_6,
        width:1,
        height:1,
        alternate:"jm_1",
        display: `Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
]